language: java
sudo: required
services:
  - docker

before_install:
  - docker build -t vneekhra/springboot-hello -f Dockerfile .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-springboot-hello"
  env: "DockerSpringbootHello-env"
  bucket_name: elasticbeanstalk-us-east-2-424816399131
  bucket_path: "docker-springboot-hello"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_KEY